test: &default
  # Update this later to sandbox cred
  # Credentials for REST APIs
  mode: sandbox
  client_id: <%= ENV["pp_client_id"] %>
  client_secret: <%= ENV["pp_client_secret"] %>

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
  client_id: <%= ENV["pp_client_id"] %>
  client_secret: <%= ENV["pp_client_secret"] %>
